version: "2"
volumes:
    archives:
    config:
    traph-data:
    mongo-data:
services:
  backend:
    image: scpomedialab/hyphe_backend:latest
    build: .
    links:
     - "mongo:mongo"
     - "crawler:crawler"
    env_file:
     - config-backend.env
    environment:
     - HYPHE_MONGODB_HOST=mongo
     - HYPHE_CRAWLER_HOST=crawler
     - HYPHE_TRAPH_DATAPATH=/app/traph-data
    volumes:
      - archives:/app/archives
      - config:/app/config
      - traph-data:/app/traph-data
  frontend:
    image: scpomedialab/hyphe_frontend:latest
    build: ./hyphe_frontend
    ports:
      - "80:80"
    links:
      - "backend:backend"
    env_file:
     - config-frontend.env
  crawler:
    image: scpomedialab/hyphe_crawler:latest
    build: ./hyphe_backend/crawler
    links:
      - "mongo:mongo"
  mongo:
    image: mongo:3.0
    volumes:
      - mongo-data:/data/db
